[package]
name = "aoc_2015"
version = "0.1.0"
authors = ["Ken <ken@kenh.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0"
md-5 = "0"
onig = "6"
ndarray = "0"
serde_json = "1"
